### ISSUE TITLE
Advance permission for users

### ISSUE THREAD

**Issue by tommy04062019** [target/goalert#2807] opened 2023-02-02 02:16 UTC
**What problem would you like to solve? Please describe:**
Currently, a normal user can do anything task like rotation, schedules, alerts. They can delete, change settings, so it is dangerous in the organization that has many users, many groups. That leads to breaking settings between different users. Also, a user should only see the resources they have subscribed to

**Describe the solution you'd like:**
A solution should be implemented such that:
- Create some permission levels for users and give access to specific resources. 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by Forfold** [comment] 2023-02-02 16:39
Closing as this is a duplicate of #700 and/or #2719

**Closed by Forfold** 2023-02-02 16:39 UTC
Labels: enhancement
