### ISSUE TITLE
Incorrect Autoupdate of Start and End Dates in Override Form

### ISSUE THREAD

**Issue by mastercactapus** [target/goalert#3456] opened 2023-11-15 18:05 UTC
**Describe the Bug:**
Changing the day input in the "Start" or "End" time fields in the Override form automatically updates the other respective field. This makes changing the exact date and time for a future schedule nearly impossible via typing in numbers.

**Steps to Reproduce:**
1. Go to an existing schedule.
2. Click "Override".
3. Click "Cover Someone's Shifts".
4. Click on the Day in the "Start" or "End" time input fields.
5. Change the Day via keyboard input (E.g. input "15" for the 15th).
6. Observe that the other date changes.
- If you change Start, then the End time changes.
- If you change End, then the Start time changes.

**Expected Behavior:**
The day input for "Start" or "End" time field should be able to be changed independently, without automatically updating the other field.

**Observed Behavior:**
Changing the start or end day leads to the automatic update of the other respective field, making it difficult to set a specific future date/time.

**Application Version:**
This issue is seen across all versions of GoAlert.

**Desktop/Browser:**
This issue has been reproduced across all browsers.

**Additional Context**
Possibly related to, or compounded by: https://github.com/target/goalert/issues/3426

**Comment by Forfold** [comment] 2023-11-15 19:23
Via typing is a duplicate of #3426, however there is also the issue of the date picker -> when selecting a month in the future (with the intention of setting the date backwards) results in the end being updates without the user wanting.

Removing validation will fix both use-cases.

**Closed** 2023-11-21 18:48 UTC
Labels: bug
